pyproject.toml
* fix: update security advisory link to point to application-sdk (#427)
* chore(release): bump version
- N/A
=> chore(release): version bump (#443)

.github/actions/unit-tests/action.yaml, .github/workflows/pull_request.yaml, .github/workflows/push.yaml
This pull request addresses issues in the documentation pipeline to ensure accurate and efficient generation of documentation for the Application SDK. The fixes aim to improve the robustness and clarity of the pipeline, aligning it with the latest updates and best practices.
- Fixed issues in the documentation pipeline.
- Updated relevant scripts or configuration files to resolve pipeline errors or inefficiencies.
- Ensured compatibility with the current structure of the repository.
The primary goal of this PR is to maintain high-quality documentation by resolving pipeline-related issues, reducing errors, and improving maintainability.
- Enhances the reliability of the documentation pipeline.
- Reduces potential delays or errors in generating or updating documentation.
- Improves …
=> docs: fix pipeline

README.md
dummy commit for release check
=> chore: update readme for release check

README.md
=> chore: test comment

README.md
=> chore: test 3

.github/workflows/tag-and-publish.yaml, Makefile, NOTICE, README.md, application_sdk/constants.py
- update docs after package publish
- N/A
---
=> chore: update docs after package publish

.github/actions/e2e-examples/action.yaml, .github/actions/setup-deps/action.yaml, .github/workflow-templates/checks.yaml, .github/workflows/pre-release.yaml, .github/workflows/release.yaml.disabled, .github/workflows/scale-tests.yaml, .github/workflows/tag-and-publish.yaml, application_sdk/test_utils/scale_data_generator/README.md, docs/docs/setup/LINUX.md, docs/docs/setup/MAC.md, docs/docs/setup/WINDOWS.md, pyproject.toml, uv.lock
- fix: uv optional dependencies and groups
---
=> fix: uv optional dependencies and groups

.cursor/rules/setup.mdc, README.md, docs/docs/guides/getting-started.md, docs/docs/setup/LINUX.md, docs/docs/setup/MAC.md, docs/docs/setup/WINDOWS.md, docs/mkdocs.yml, uv.lock
- Make docs simpler to navigate
- remove pyenv dependency - use `uv` to configure the python environment
---
=> chore: update docs

application_sdk/common/logger_adaptors.py
- Fixed pre-commit related errors on develop
LInk : https://atlanhq.slack.com/archives/C07A8R56R2A/p1747293071842169?thread_ts=1747293051.275489&cid=C07A8R56R2A
---
=> fix : LoggerAdaptor related errors

application_sdk/inputs/sql_query.py
Fixed pandas import in SqlQueryInput class
pandas was added only in `TYPECHECKING`. However the actual import needs to be present wherever the pandas module is used.
Otherwise we get errors saying `pandas not found`
---
=> fix: pandas import in SqlQueryInput class

application_sdk/application/metadata_extraction/sql.py, application_sdk/clients/temporal.py
Improve the collection of workflow activities by aggregating them from all workflow classes and introduce a customizable output prefix for workflow execution.
=> Enhance workflow activity collection and allow custom output prefix

application_sdk/common/logger_adaptors.py, tests/unit/common/test_logger_adapter.py
- Temporal context was not being interpolated on the logs
- This included context for workflow and activities both
- Fixed by using f-strings
JIRA : https://atlanhq.atlassian.net/browse/APP-6790
---
=> fix : APP-6790

pyproject.toml
- Added duckdb and duckdb-engine as dependencies
- Removed it from scale_data_generator module in application-sdk pyproject.toml
JIRA : https://atlanhq.atlassian.net/browse/APP-6789
---
=> fix : APP-6789

docs/docs/setup/LINUX.md, docs/docs/setup/MAC.md
- docs: add common setup issues
---
=> docs: add common setup issues

.gitignore, .vscode/launch.json, README.md, docs/docs/guides/partners.md, docs/docs/setup/LINUX.md, docs/docs/setup/MAC.md, docs/docs/setup/WINDOWS.md, docs/docs/setup/troubleshooting.md, examples/README.md
- improvements to documentation and debugging
---
=> docs: improvements to documentation and debugging

.github/actions/trivy/action.yaml
- Removed slack notification logic from trivy. offloading that capability to Synk.
JIRA : https://atlanhq.atlassian.net/browse/APP-6323
---
=> chore: APP-6323 Update Security Alerts

application_sdk/outputs/eventstore.py
- Removing warning logs when events are published outside workflow / activity context
---
=> fix: switch to debug level for logs outside workflow/activity context

application_sdk/handlers/sql.py, application_sdk/server/fastapi/__init__.py, examples/application_fastapi.py
- fix defaults for `fetch_metadata` endpoint
- simplify `fetch_metadata` handler
- This would earlier fail with KeyError in case a `type: all` result is required and the user doesn't pass the database
---
=> fix: defaults for fetch_metadata endpoint, simplify handler

.github/actions/e2e-examples/action.yaml, .github/actions/setup-deps/action.yaml, .github/actions/unit-tests/action.yaml, .github/workflows/pull_request.yaml, .github/workflows/push.yaml, .github/workflows/tag-and-publish.yaml, .gitignore, examples/run_examples.py, pyproject.toml, tests/unit/common/test_logger_adapter.py
- enable e2e examples and unit tests on linux, macOS and windows
---
=> feat: enable tests and examples on macOS and windows as part of CI

application_sdk/common/utils.py, tests/unit/common/test_utils.py
- Added a fix based on the assumption, that whenever the include filter is left blank / empty, it means that we want to include everything.
---
=> fix: include databases in common/utils

.cursor/BUGBOT.md
- add a minimal `.cursor/BUGBOT.md` file, this will evolve as cursor improves BUGBOT and we have more understanding of how BUGBOT picks up the context from the defined rules and repository.
---
=> chore: add a minimal .cursor/BUGBOT.md file

application_sdk/inputs/objectstore.py
- fix: download_files_from_object_store with correct files list
---
=> fix: download_files_from_object_store with correct files list

.cursor/BUGBOT.md, application_sdk/outputs/objectstore.py
- An attempt to fix the cursor rules cross context reference.
---
=> fix: file references in cursor rules

.cursor/BUGBOT.md, application_sdk/activities/.cursor/BUGBOT.md, application_sdk/clients/.cursor/BUGBOT.md, application_sdk/common/.cursor/BUGBOT.md, application_sdk/decorators/.cursor/BUGBOT.md, application_sdk/inputs/.cursor/BUGBOT.md, application_sdk/interceptors/.cursor/BUGBOT.md, application_sdk/outputs/.cursor/BUGBOT.md, application_sdk/server/.cursor/BUGBOT.md, application_sdk/workflows/.cursor/BUGBOT.md, tests/.cursor/BUGBOT.md
=> feat: enhance bugbot rules

.github/ISSUE_TEMPLATE/bug_report.yaml, .github/ISSUE_TEMPLATE/feature_request.yaml
=> chore: fix issues templates

docs/docs/concepts/API.md
- add minimal API docs for endpoints exposed
---
=> docs: add minimal API docs for endpoints exposed

.github/scripts/update_changelog.py
- Updates the changelog script to use the `gh api` command instead of `git log`.
- Fetches the author's GitHub username (`.author.login`) for correct attribution in the `CHANGELOG.md` file.
- Fixes a bug where the script compared the last version tag to `HEAD`, ensuring it now accurately compares the two specific tags provided.
- Hardcodes the `atlanhq/application-sdk` repository to generate correct URLs for commits and the full changelog, regardless of the user's local fork.
- This resolves the issue where author names were used instead of usernames in Changelog.md.
- Closes #717
-Screenshot of local output:- 
- Comparing it to the actual changelog from the main repo:
---
=> fix: Make Changelog script use GitHub usernames instead of Git Author Names
